name: Summarize new issues

on:
  issues:
    types: [opened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Summarize the following GitHub issue in one paragraph:
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}

      - name: Comment with AI summary
        run: |
          gh issue comment $ISSUE_NUMBER --body '${{ steps.inference.outputs.response }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          RESPONSE: ${{ steps.inference.outputs.response }}
                      - الاسم: إعداد .NET Core SDK
  الاستخدامات: actions/setup-dotnet@v5.0.0
  مع:
    # إصدارات SDK اختيارية للاستخدام. في حال عدم توفرها، سيتم تثبيت إصدار global.json عند توفره. أمثلة: 2.2.104، 3.1، 3.1.x، 3.x، 6.0.2xx
    dotnet-version: # اختياري
    جودة البناء اختيارية. القيم الممكنة هي: يوميًا، مُوقّع، مُصدّق، معاينة، ga.
    dotnet-quality: # اختياري
    # موقع global.json اختياري، إذا لم يكن global.json موجودًا في جذر المستودع.
    global-json-file: # اختياري
    # مصدر حزمة اختياري لإعداد المصادقة. سيراجع أي ملف NuGet.config موجود في جذر المستودع، ويوفر ملف NuGet.config مؤقتًا باستخدام متغير البيئة NUGET_AUTH_TOKEN ككلمة مرور ClearTextPassword.
    عنوان URL المصدر: # اختياري
    # مالك اختياري لاستخدام الحزم من منظمات/مستخدمي سجل حزم GitHub بخلاف مالك المستودع الحالي. يُستخدم فقط إذا تم توفير عنوان URL لـ GPR في عنوان URL المصدر.
    المالك: # اختياري
    # موقع NuGet.config اختياري، إذا لم يكن NuGet.config موجودًا في جذر المستودع.
    ملف التكوين: # اختياري
    # إدخال اختياري لتمكين التخزين المؤقت لمجلد NuGet global-packages
    ذاكرة التخزين المؤقت: # اختياري
    # يُستخدم لتحديد مسار ملف التبعيات: packages.lock.json. يدعم استخدام أحرف بديلة أو قائمة بأسماء الملفات لتخزين تبعيات متعددة مؤقتًا.
    مسار اعتماد ذاكرة التخزين المؤقت: # اختياري
          
